title: Devvit Research
email: miagobble@duck.com
description: A joint program between iGottic and Devvit to create easily accessible research about the Roblox platform
author: Mia Gobble
baseurl: "/"
url: "https://research.igottic.com"
twitter_username: iGottic_Real
github_username: MiaGobble

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
